### ISSUE TITLE
Feature request: include package name or package url in arrow metadata

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/Legolas.jl#46]
Since Legolas schemas are defined in code, if you just have a table, `Legols.read` will tell you the schema isn't defined and you need to load the package, but it won't tell you *which* package (brought up by @a-cakir in the engineering roundtable). Namespacing can help, but it could be more clear if we actually just put the julia module name where the `@row` was defined, and/or the package name, and/or the repo url. We could put this in the Arrow metadata and use it to give a more precise error message.

**Comment by hannahilea** [comment]
this would be a game-changer!

**Comment by jrevels** [comment]
probably a good idea

also ref https://github.com/beacon-biosignals/Legolas.jl/issues/1

**Comment by jrevels** [comment]
xref https://github.com/beacon-biosignals/Legolas.jl/pull/54#discussion_r1005592514

**Comment by ericphanson** [comment]
just to bump this; I think we should have some metadata at least for julia users to know what package provides a schema, so undefschema errors can say "load package X".

(came up in an internal project)
